[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JointModels = "54f05ff3-c196-4f1a-acfd-0c2b8e4405db"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Survival = "8a913413-2070-5976-9d4c-2b364fdc2f7f"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
